CREATE DATABASE IF NOT EXISTS bd_mundo CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE bd_mundo;
CREATE TABLE IF NOT EXISTS paises (
  id_pais INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  continente VARCHAR(100) NOT NULL,
  populacao BIGINT UNSIGNED DEFAULT 0,
  idioma VARCHAR(100) DEFAULT NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS cidades (
  id_cidade INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  populacao BIGINT UNSIGNED DEFAULT 0,
  id_pais INT NOT NULL,
  FOREIGN KEY (id_pais) REFERENCES paises(id_pais)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE=InnoDB;
CREATE INDEX idx_cidades_pais ON cidades(id_pais);
